# Generated by Django 4.2.4 on 2023-08-20 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account_invited_user_account_referral_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='invited_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
    ]
