# Generated by Django 4.2.4 on 2023-08-20 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_account_invited_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='referral_user',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='WhoInviteMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
