# Generated by Django 4.2.4 on 2023-08-20 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_referrals_referrals_alter_referrals_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='user_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
    ]
